### ISSUE TITLE
RH CDM PEM file missing

### ISSUE THREAD

**Issue by dmc5179** [openshift/quay-image-builder#33]
The build scripts have been updated resulting in the rh-cdn.pem file being an empty file.

- There is no rh-cdn.pem in git for obvious reasons. This was always something that had to be added to the build manually
- The build.sh script uses sed to replace the placeholder CDN_PEM_CONTENT with the pem file contents.

The scripts are all out of alignment for the PEM resulting in an empty PEM file which will ensure none of the repos will work which is why podman is not installed before being run in cloud-config.sh even though there is a dnf command to install podman first.

**Comment by bparry02** [comment]
Recall that the rh-cdn.pem is required for our build environment since we are building a marketplace AMI that does not have access to RHUI. The CI build takes care of inserting the rh-cdn.pem.

For building outside the CI environment, a flag has been added that will skip the attempt to reconfigure the yum repositories and just use the pre-configured RHUI repos. This works for Cloud Access AMIs and Hourly AMIs.

https://github.com/openshift/quay-image-builder/blob/main/build.sh#L139
https://github.com/openshift/quay-image-builder/blob/main/cloud-config.sh.template#L66

Try running build.sh with:
```
SOURCE_AMI=ami-09a9d44aaf636d415 REPLACE_AMI_YUM_CONFIG=false  [ ... other params ...] ./build.sh
```

**Comment by bparry02** [comment]
Closing stale issue
